<template>
  <div class="TelephoneP_content">
    <table-List :thead="tHead" :tData="tData" :PageInfo="PageInfo" :showSearch="showSearch" :headerTitle="headerTitle" :showPageF="showSearch"></table-List>
  </div>
</template>
<script>
  import  tableList from  '../../component/tablelist.vue';
  export default{
    data(){
        return {
          tHead:[
            {
              title:"序号",
              key:'index'
            },
            {
              title:"姓名",
              key:'name'
            },
            {
              title:"职位",
              key:'position'
            },
            {
              title:"手机号",
              key:'phone'
            },
            {
              title:"QQ",
              key:'qqnumber'
            },
            {
              title:"Email",
              key:'email'
            },
          ],
          tData:[
            {
              index:2,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:3,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:4,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:5,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:6,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:7,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:8,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:9,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            },
            {
              index:10,
              name:'王鹏',
              position:'前端专员',
              phone:187215231,
              qqnumber:118396308,
              email:123123123
            }
          ],
          PageInfo:100,
          showSearch:true,
          headerTitle:"员工信息"
        }
    },
    mounted () {},
    components:{
      "tableList":tableList,
    },
  }
</script>
<style>
  .TelephoneP_content{}
</style>
